/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yunos_assistant_ui_card_ImageUtilEngine */

#ifndef _Included_com_yunos_assistant_ui_card_ImageUtilEngine
#define _Included_com_yunos_assistant_ui_card_ImageUtilEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yunos_assistant_ui_card_ImageUtilEngine
 * Method:    stackBlur
 * Signature: ([IIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yunos_assistant_ui_card_ImageUtilEngine_stackBlur
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jint);

/*
 * Class:     com_yunos_assistant_ui_card_ImageUtilEngine
 * Method:    isBlackBackground
 * Signature: ([III)I
 */
JNIEXPORT jint JNICALL Java_com_yunos_assistant_ui_card_ImageUtilEngine_isBlackBackground
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
